mv "Baseball-Game.py" "682.-Baseball-Game.py"
mv "Decode-String.py" "394.-Decode-String.py"
mv "Implement-Stack-Using-Queues.py" "225.-Implement-Stack-Using-Queues.py"
mv "Remove-All-Adjacent-Duplicates-in-String.py" "1047.-Remove-All-Adjacent-Duplicates-in-String.py"
mv "Removing-Stars-From-a-String.py" "2390.-Removing-Stars-From-a-String.py"
